<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_2</name>
   <tag></tag>
   <elementGuidId>d67b92d9-b632-4358-9ead-1677f7c69230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='fadein']/section/div/div/div/div[2]/div[2]/div/div/div[2]/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0f6d01c6-2b65-4f0d-bc3a-1e9abbb3af93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>info__title</value>
      <webElementGuid>e6b80c5e-b6bc-49ce-b342-edeffa4aa401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>83fcf3b6-b4a6-49bc-a9c1-4f6860869507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fadein&quot;)/section[@class=&quot;dashboard-area&quot;]/div[@class=&quot;dashboard-content-wrap&quot;]/div[@class=&quot;dashboard-bread&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-lg-3 responsive-column-m&quot;]/div[@class=&quot;icon-box icon-layout-2 dashboard-icon-box&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;info-content&quot;]/h4[@class=&quot;info__title&quot;]</value>
      <webElementGuid>8c7a94a3-bc79-4087-88c4-3c9a39ca80a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fadein']/section/div/div/div/div[2]/div[2]/div/div/div[2]/h4</value>
      <webElementGuid>dfd75b1f-f85e-4f50-8ed1-a0afd6620365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD 1500'])[1]/following::h4[1]</value>
      <webElementGuid>a935a8e3-c443-4756-b037-25bdae902ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo'])[2]/following::h4[2]</value>
      <webElementGuid>f14736a6-724e-479e-8b26-07b5cf48bc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Searches'])[1]/preceding::h4[3]</value>
      <webElementGuid>e680dd3c-e10c-4c05-84ab-76c74ab2efb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Help? Contact us'])[1]/preceding::h4[3]</value>
      <webElementGuid>858bac47-d9d0-4f83-a516-e5d65173a6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>6bdb6bb2-1932-47ad-aba9-33fd0a5b6667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/h4</value>
      <webElementGuid>5929e588-4eea-4963-8171-822524416d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '2' or . = '2')]</value>
      <webElementGuid>9b37f8d9-6009-4a8c-98a5-51d688aa089e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
